server:
  port: ${PAGOPA_BACKOFFICE_SERVER_PORT:8080}
  shutdown: GRACEFUL

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  profiles:
    include:
      - swaggerEN

info:
  env: ${ENV:}
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"



logging:
  level:
    it.pagopa.selfcare.pagopa: ${PAGOPA_BACKOFFICE_LOG_LEVEL:DEBUG}
