oa3_spec: ./openapi/openapi.json
name: opex_pagopa-selfcare-ms-backoffice
location: West Europe
timespan: 5m
data_source: /subscriptions/bbe47ad4-08b3-4925-94c5-1278e5819b86/resourceGroups/pagopa-d-vnet-rg/providers/Microsoft.Network/applicationGateways/pagopa-d-app-gw
action_groups:
  - /subscriptions/bbe47ad4-08b3-4925-94c5-1278e5819b86/resourceGroups/pagopa-d-monitor-rg/providers/microsoft.insights/actionGroups/PagoPA
  - /subscriptions/bbe47ad4-08b3-4925-94c5-1278e5819b86/resourceGroups/pagopa-d-monitor-rg/providers/microsoft.insights/actionGroups/SlackPagoPA
overrides:
  hosts:
    - api.dev.platform.pagopa.it
