microservice-chart:
  namespace: "selfcare"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-selfcare-ms-backoffice-backend
    tag: "2.36.6-3-PIDM-441-va-pt-step-1"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 80 #http
    - 12345 #jmx-exporter
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.selfcare.internal.dev.platform.pagopa.it"
    path: "/selfcare/pagopa/v1/(.*)"
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaselfcaremsbackofficebackend'
    EXTERNAL_API_SERVICE_URL: https://api.dev.selfcare.pagopa.it
    PAGOPA_APIM_SERVICE_URL: https://api.dev.platform.pagopa.it
    PAGOPA_SELFCARE_INTEGRATION_APIM_SERVICE_URL: https://api.dev.platform.pagopa.it
    GEC_SERVICE_URL: https://api.dev.platform.pagopa.it
    FORWARDER_SERVICE_URL: https://api.dev.platform.pagopa.it
    TAXONOMY_SERVICE_URL: https://api.platform.pagopa.it
    ENABLE_SEND_EMAIL: 'false'
    AZURE_RESOURCE_GROUP: pagopa-d-api-rg
    AZURE_SERVICE_NAME: pagopa-d-apim
    APPCONFIGURATION_ENDPOINT: 'https://pagopa-d-selfcare-appconfiguration.azconfig.io'
    ENABLE_CONFIDENTIAL_FILTER: 'FALSE'
    MONGODB_NAME: pagopaBackoffice
    AUTHORIZATION_FLAG: 'false'
    ENV: 'DEV'
    REST_CLIENT_LOGGER_LEVEL: 'FULL'
    AWS_REGION: 'eu-south-1'
    AWS_QUICKSIGHT_REGION: 'eu-west-1'
    AWS_QUICKSIGHT_NAMESPACE: 'default'
    AWS_QUICKSIGHT_ALLOWED_DOMAINS: 'https://selfcare.dev.platform.pagopa.it'
    AWS_QUICKSIGHT_SESSION_TAG_KEY: 'institution_id'
    OTEL_SERVICE_NAME: "pagopa-selfcare-backoffice-backend"
    CRONJOB_SCHEDULE_ENABLED: 'true'
    CRONJOB_SCHEDULE_TAXONOMYEXPORT: "0 0 7 * * *"
    CRONJOB_SCHEDULE_IBANEXPORT: "0 0 1 * * *"
    CRONJOB_SCHEDULE_CIEXPORT: "0 0 3 * * *"
    EXTRACTION_IBANS_GETBROKERS_LIMIT: '200'
    EXTRACTION_IBANS_GETIBANS_LIMIT: '500'
    EXTRACTION_IBANS_GETCIBYBROKER_LIMIT: '1000'
    EXTRACTION_IBANS_CLEAN_OLDERTHANDAYS: '7'
    EXTRACTION_IBANS_PERSISTIBANBATCHSIZE: '8000'
    EXTRACTION_IBANS_EXPORTAGAINAFTERHOURS: '0'
    CLIENT_RETRY_MAX_ATTEMPTS: '3'
    CLIENT_RETRY_MAX_DELAY: '2000'
  envSecret:
    AWS_ACCESS_KEY_ID: pagopa-d-aws-access-key-id
    AWS_SECRET_ACCESS_KEY: pagopa-d-aws-secret-access-key
    AWS_SES_USER: pagopa-d-aws-ses-user
    AWS_QUICKSIGHT_ACCESS_KEY: pagopa-d-aws-quicksight-access-key
    AWS_QUICKSIGHT_SECRET_KEY: pagopa-d-aws-quicksight-secret-key
    AWS_QUICKSIGHT_ACCOUNT_ID: pagopa-d-aws-quicksight-account-id
    AWS_QUICKSIGHT_DASHBOARD_ID: pagopa-d-aws-quicksight-dashboard-id
    AZURE_CLIENT_SECRET: pagopa-d-selfcare-client-secret
    AZURE_CLIENT_ID: pagopa-d-selfcare-client-id
    AZURE_TENANT_ID: pagopa-selfcare-dev-tenant-id
    AZURE_SUBSCRIPTION_ID: pagopa-selfcare-d-subscription-id
    SELFCARE_APIM_EXTERNAL_API_KEY_PAGOPA: selfcare-d-apim-external-api-key
    PAPGOPA_APIM_GEC_API_KEY_PAGOPA: pagopa-d-apim-gec-key
    PAPGOPA_APIM_GPD_API_KEY_PAGOPA: pagopa-d-apim-gpd-key
    PAPGOPA_APIM_TAXONOMY_API_KEY_PAGOPA: pagopa-d-apim-taxonomy-key
    PAPGOPA_APIM_FORWARDER_API_KEY_PAGOPA: pagopa-d-apim-forwarder-key
    PAGOPA_APIM_API_CONFIG_API_KEY_PAGOPA: pagopa-d-apim-api-config-key
    PAGOPA_APIM_API_CONFIG_SELFCARE_INTEGRATION_API_KEY_PAGOPA: pagopa-d-apim-api-config-selfcare-integration-key
    PAPGOPA_APIM_AUTHORIZER_CONFIG_API_KEY_PAGOPA: pagopa-d-apim-authorizer-config-key
    PAPGOPA_APIM_INSTITUTIONS_API_KEY_PAGOPA: pagopa-d-apim-notices-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    JWT_TOKEN_PUBLIC_KEY: pagopa-d-weu-selfcare-jwt-pub-key
    TEST_EMAIL: pagopa-d-env-test-email
    MONGODB_CONNECTION_URI: cosmodbmongo-d-bopagopa-connection-string
    JIRA_URL: jira-d-url
    JIRA_USERNAME: jira-d-username
    JIRA_PASSWORD: jira-d-token
    JIRA_PROJECT_KEY: jira-d-project-key
    JIRA_REQ_TYPE_TASKID: jira-d-req-task-id
    OTEL_EXPORTER_OTLP_HEADERS: elastic-apm-secret-token
    PAGOPA_OPERATOR_EMAIL: pagopa-d-env-operator-email
  keyvault:
    name: "pagopa-d-selfcare-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-selfcare-ms-backoffice-backend
        tag: 2.14.1-1-hotfix-timout-feign
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
