microservice-chart:
  namespace: "selfcare"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaselfcaremsbackofficebackend
    tag: "0.0.112" #improve
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080 #80
  ingress:
    create: true
    host: "weudev.selfcare.internal.dev.platform.pagopa.it"
    path: "/selfcare/pagopa/v1/(.*)"
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaselfcaremsbackofficebackend'
    EXTERNAL_API_SERVICE_URL: https://api.dev.selfcare.pagopa.it
    PAGOPA_APIM_SERVICE_URL: https://api.dev.platform.pagopa.it
    AZURE_RESOURCE_GROUP: pagopa-d-api-rg
    AZURE_SERVICE_NAME: pagopa-d-apim
    ENABLE_CONFIDENTIAL_FILTER: 'FALSE'
    MONGODB_NAME: pagopaBackoffice
  envSecret:
    AZURE_CLIENT_SECRET: pagopa-d-selfcare-client-secret
    AZURE_CLIENT_ID: pagopa-d-selfcare-client-id
    SELFCARE_APIM_EXTERNAL_API_KEY_PAGOPA: selfcare-d-apim-external-api-key
    PAGOPA_APIM_API_CONFIG_API_KEY_PAGOPA: pagopa-d-apim-api-config-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    AZURE_TENANT_ID: pagopa-selfcare-dev-tenant-id
    AZURE_SUBSCRIPTION_ID: pagopa-selfcare-d-subscription-id
    JWT_TOKEN_PUBLIC_KEY: pagopa-d-weu-selfcare-jwt-pub-key
    TEST_EMAIL: pagopa-d-env-test-email
    MONGODB_CONNECTION_URI: cosmodbmongo-d-bopagopa-connection-string
  keyvault:
    name: "pagopa-d-selfcare-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
