microservice-chart:
  namespace: "selfcare"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopaucommonacr.azurecr.io/pagopaselfcaremsbackofficebackend
    tag: "0.0.150" #improve
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    port: 8080 #80
  ingress:
    create: true
    host: "weuuat.selfcare.internal.uat.platform.pagopa.it"
    path: "/selfcare/pagopa/v1/(.*)"
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.5"
    limits:
      memory: "768Mi"
      cpu: "0.5"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    WEBSITE_SITE_NAME: 'pagopaselfcaremsbackofficebackend'
    EXTERNAL_API_SERVICE_URL: https://api.uat.selfcare.pagopa.it
    PAGOPA_APIM_SERVICE_URL: https://api.uat.platform.pagopa.it
    PAGOPA_SELFCARE_INTEGRATION_APIM_SERVICE_URL: https://api.uat.platform.pagopa.it
    AZURE_RESOURCE_GROUP: pagopa-u-api-rg
    AZURE_SERVICE_NAME: pagopa-u-apim
    ENABLE_CONFIDENTIAL_FILTER: 'FALSE'
    MONGODB_NAME: pagopaBackoffice
    AUTHORIZATION_FLAG: 'false'
    ENV: 'UAT'
  envSecret:
    AZURE_CLIENT_SECRET: pagopa-u-selfcare-client-secret
    AZURE_CLIENT_ID: pagopa-u-selfcare-client-id
    SELFCARE_APIM_EXTERNAL_API_KEY_PAGOPA: selfcare-u-apim-external-api-key
    PAGOPA_APIM_API_CONFIG_API_KEY_PAGOPA: pagopa-u-apim-api-config-key
    PAGOPA_APIM_API_CONFIG_SELFCARE_INTEGRATION_API_KEY_PAGOPA: pagopa-u-apim-api-config-selfcare-integration-key
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-u-connection-string'
    AZURE_TENANT_ID: pagopa-selfcare-uat-tenant-id
    AZURE_SUBSCRIPTION_ID: pagopa-selfcare-u-subscription-id
    JWT_TOKEN_PUBLIC_KEY: pagopa-u-weu-selfcare-jwt-pub-key
    TEST_EMAIL: pagopa-u-env-test-email
    MONGODB_CONNECTION_URI: cosmodbmongo-u-bopagopa-connection-string
    JIRA_URL: jira-u-url
    JIRA_USERNAME: jira-u-username
    JIRA_PASSWORD: jira-u-token
    JIRA_PROJECT_KEY: jira-u-project-key
    JIRA_REQ_TYPE_TASKID: jira-u-req-task-id
  keyvault:
    name: "pagopa-u-selfcare-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity: {}
