name: CD Next Release

on:
  push:
    branches:
      - next


permissions:
  packages: write
  contents: write
  issues: write
  id-token: write
  actions: read


jobs:

  image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - id: get_app_version
        name: Get Version
        run: |
          echo "version=$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Login to GitHub Container Registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # v4.3.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            ${{ steps.get_app_version.outputs.version }}
            type=ref,event=branch
            type=sha

      - name: Build and push
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_aks:
    name: Deploy in DEV
    needs: [ image ]
    uses: ./.github/workflows/deploy_with_github_runner.yml
    with:
      environment: "dev"
    secrets: inherit


