name: CD Develop

on:
  pull_request:
    branches:
      - next
    types:
      - closed


permissions:
  packages: write
  contents: write
  issues: write
  id-token: write
  actions: read


jobs:
  pre_release:
    name: Create a New Pre-Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Make Release
        id: release
        uses: pagopa/github-actions-template/maven-release@473d7a78d28e15cab46dcaf766087e60604d6a40 # v1.13.3
        with:
          semver: buildNumber
          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}
          beta: false
          skip_ci: false
          prerelease: true
          only_tag: true

  image:
    needs: [ pre_release ]
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push
        uses: pagopa/github-actions-template/ghcr-build-push@d91a1fd0b913c9830589be5d86cdb71c90813fae # v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.pre_release.outputs.version }}

  deploy:
    name: Deploy in DEV
    needs: [ image ]
    uses: ./.github/workflows/deploy_with_github_runner.yml
    with:
      environment: 'dev'
    secrets: inherit


