name: Code Review

# Controls when the workflow will run
on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_KEY: pagopa_pagopa-selfcare-ms-backoffice-backend

permissions:
  id-token: write
  contents: write
  deployments: write
  issues: write
  pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-review:
    name: Code Review
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test and Coverage
        uses: pagopa/github-actions-template/maven-code-review@v1.10.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          project_key: ${{env.PROJECT_KEY}}
          coverage_exclusions: "**/config/*,**/*Mock*,**/model/**,**/entity/*,**/exception/*"
          cpd_exclusions: "**/model/**,**/entity/*"
          java_version: 17

  image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push
        uses: pagopa/github-actions-template/ghcr-build-push@v1.5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.number }}

  deploy:
    name: Deploy in DEV
    needs: [ image ]
    uses: ./.github/workflows/deploy_with_github_runner.yml
    with:
      environment: 'dev'
      options: '--set=fullnameOverride=pagopaselfcaremsbackofficebackend-${{ github.event.number }} --set=image.tag=${{ github.event.number }} --set=ingress.path=/selfcare/pagopa/${{ github.event.number }}/(.*)'
    secrets: inherit

  smoke_test:
    name: Smoke Test
    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    uses: ./.github/workflows/ci_integration_test.yml
    with:
      environment: 'local'
      notify: false
    secrets: inherit
