name: Code Review

# Controls when the workflow will run
on:
  merge_group:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_KEY: pagopa_pagopa-selfcare-ms-backoffice-backend

permissions:
  id-token: write
  contents: read
  deployments: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-review:
    name: Code Review
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test and Coverage
        uses: pagopa/github-actions-template/maven-code-review@v1.10.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          project_key: ${{env.PROJECT_KEY}}
          coverage_exclusions: "**/config/*,**/*Mock*,**/model/**,**/entity/*,**/exception/*"
          cpd_exclusions: "**/model/**,**/entity/*"
          java_version: 17

  smoke_test:
    name: Smoke Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.DEV_CLIENT_ID }}
          tenant-id: ${{ secrets.DEV_TENANT_ID }}
          subscription-id: ${{ secrets.DEV_SUBSCRIPTION_ID }}

      - name: Run Service on Docker
        shell: bash
        id: run_service_docker
        run: |
          cd ./docker
          chmod +x ./run_docker.sh
          ./run_docker.sh local

      - name: Run Integration Tests
        shell: bash
        id: run_integration_test
        run: |
          export SUBKEY=${{ secrets.DEV_SUBKEY }}
          export CANARY=${{ inputs.canary }}
          export CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

          cd ./integration-test
          chmod +x ./run_integration_test.sh
          ./run_integration_test.sh local



