name: Integration Tests

on:
#  schedule:
#    - cron: '00 08 * * 1-5'

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Select the Environment
      canary:
        description: 'run the tests on canary version'
        required: false
        type: boolean
        default: false
      notify:
        required: false
        type: boolean
        description: 'send the slack notification'
        default: true
  
  
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
      canary:
        description: 'run the tests on canary version'
        required: false
        type: boolean
        default: false
      notify:
        required: false
        type: boolean
        description: 'send the slack notification'
        default: true


permissions:
  id-token: write
  contents: read
  deployments: write


jobs:
  integration_test:
    name: Test ${{(github.event.inputs == null && 'dev') || inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: setup
        id: setup
        run: |
          echo "CLIENT_ID=${{DEV_CLIENT_ID}}" >> $GITHUB_ENV 
          echo "TENANT_ID=${{DEV_TENANT_ID}}" >> $GITHUB_ENV 
          echo "SUBSCRIPTION_ID=${{DEV_SUBSCRIPTION_ID}}" >> $GITHUB_ENV 
          echo "SUBKEY=${{DEV_SUBKEY}}" >> $GITHUB_ENV 
          
          if [[ ${{ inputs.environment }} == "uat" ]]; then
            echo "CLIENT_ID=${{UAT_CLIENT_ID}}" >> $GITHUB_ENV 
            echo "TENANT_ID=${{UAT_TENANT_ID}}" >> $GITHUB_ENV 
            echo "SUBSCRIPTION_ID=${{UAT_SUBSCRIPTION_ID}}" >> $GITHUB_ENV 
            echo "SUBKEY=${{UAT_SUBKEY}}" >> $GITHUB_ENV 
          fi

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ env.CLIENT_ID }}
          tenant-id: ${{ env.TENANT_ID }}
          subscription-id: ${{ env.SUBSCRIPTION_ID }}

      - name: Run Integration Tests
        shell: bash
        run: |
          export SUBKEY=${{ env.SUBKEY }}
          export CANARY=${{ inputs.canary }}
          export CUCUMBER_PUBLISH_TOKEN=${{ secrets.CUCUMBER_PUBLISH_TOKEN }}

          cd ./integration-test
          chmod +x ./run_integration_test.sh
          ./run_integration_test.sh ${{( github.event.inputs == null && 'dev') || inputs.environment }}

  notify:
    needs: [ integration_test ]
    runs-on: ubuntu-latest
    name: Notify
    if: ${{ always() && (inputs.notify == 'true' && github.event_name == 'schedule')  }}
    steps:
      - name: Report Status
        if: ${{ inputs.notify }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ needs.integration_test.result }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notify_when: 'failure,skipped'
          notification_title: '<{run_url}|Scheduled Integration Test> has {status_message}'
          message_format: '{emoji} <{run_url}|{workflow}> {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to <{workflow_url}| workflow file>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


